## 행정동별 가중치 구하기
천안시 연령병 인구현황 데이터를 통해 행정동별 18~39세 인구를 통해 가중치 구하기<br>
가중치: 정규화 (minmax scaling)

In [3]:
import pandas as pd
file_path = "./data/연령별인구현황.xlsx"
df = pd.read_excel(file_path, sheet_name="1. 천안시 연령별 인구(2024.6월)", skiprows=5)

In [5]:
df = df.drop('Unnamed: 1', axis=1)

In [7]:
df_no_na = df.dropna(subset=['연    령'])

In [9]:
new_df = df_no_na[['연    령', '목천읍', '풍세면', '광덕면', '북면', '성남면', '수신면',
       '병천면', '동면', '중앙동', '문성동', '원성1동', '원성2동', '봉명동', '일봉동', '신방동', '청룡동',
       '신안동', '성환읍', '성거읍', '직산읍', '입장면', '성정1동', '성정2동', '쌍용1동',
       '쌍용2동', '쌍용3동', '백석동', '불당1동', '불당2동', '부성1동', '부성2동']]

In [11]:
myindex = list(range(58, 122, 3))

In [13]:
new_df = new_df.loc[myindex]

In [21]:
cnt = new_df.sum()

In [23]:
cnt_df = pd.DataFrame(cnt, columns=['개수'])

In [25]:
cnt_df = cnt_df.iloc[1:]
cnt_df

         개수
목천읍    4883
풍세면    2353
광덕면     541
북면      586
성남면     361
수신면     309
병천면    1290
동면      185
중앙동     966
문성동    2553
원성1동   1729
원성2동   1963
봉명동    4780
일봉동    4926
신방동   12523
청룡동   16529
신안동   14100
성환읍    4502
성거읍    5217
직산읍    5079
입장면    1397
성정1동   5049
성정2동  11520
쌍용1동   3907
쌍용2동  10709
쌍용3동   4750
백석동   10821
불당1동  10599
불당2동  11131
부성1동  21596
부성2동  21827

In [27]:
cnt_df = cnt_df.reset_index()

In [29]:
cnt_df.rename(columns={"index":"동"}, inplace=True)

In [31]:
cnt_df["가중치"] = (cnt_df["개수"]-cnt_df["개수"].min())/(cnt_df["개수"].max()-cnt_df["개수"].min())

In [33]:
cnt_df

       동     개수       가중치
0    목천읍   4883  0.217078
1    풍세면   2353  0.100176
2    광덕면    541  0.016449
3     북면    586  0.018529
4    성남면    361  0.008132
5    수신면    309   0.00573
6    병천면   1290  0.051058
7     동면    185       0.0
8    중앙동    966  0.036087
9    문성동   2553  0.109417
10  원성1동   1729  0.071343
11  원성2동   1963  0.082155
12   봉명동   4780  0.212319
13   일봉동   4926  0.219065
14   신방동  12523  0.570095
15   청룡동  16529  0.755198
16   신안동  14100  0.642963
17   성환읍   4502  0.199473
18   성거읍   5217  0.232511
19   직산읍   5079  0.226134
20   입장면   1397  0.056002
21  성정1동   5049  0.224748
22  성정2동  11520   0.52375
23  쌍용1동   3907   0.17198
24  쌍용2동  10709  0.486277
25  쌍용3동   4750  0.210932
26   백석동  10821  0.491452
27  불당1동  10599  0.481194
28  불당2동  11131  0.505776
29  부성1동  21596  0.989326
30  부성2동  21827       1.0

In [35]:
cnt_df.to_csv("./data/cnt_df.csv", index=False)